### PR TITLE
Resolving issue#30 for antidot-framework

### PR DESCRIPTION
**Pull request by peter279k**
## Description

It's related to https://github.com/antidot-framework/antidot-framework/issues/30.

## Motivation and context

As the above issue.

## How has this been tested?
N/A

## Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by peter279k** [comment]
Just notice that this PR is for the BC break and it should cause static analysis tool (Psalm) has issues.

**Comment by kpicaza** [comment]
We need the change in the Application interface first to be able to pass the pipeline. Nice work;-D

**Comment by kpicaza** [comment]
@dependabot rebase

**Comment by kpicaza** [comment]
Hi @peter279k, I merged the breaking change in the main branch. You need to rebase the main branch with your current branch(I can't rebase from the UI).

```bash
git checkout 2.x.x
git fetch
git pull [REMOTE_NAME] 2.x.x
git checkout fix_route_param_orders
git rebase 2.x.x
git push origin fix_route_param_orders --force-with-lease 
``` 

I think that it should fix every step in the pipeline. Thanks for your great work;-D

**Review by kpicaza — APPROVED** [review]

**Comment by peter279k** [comment]
@kpicaza, sorry. I almost forget that. Is there any problem when merging this PR?

**Comment by kpicaza** [comment]
No, there is another breaking change from an internal perspective I added in this PR https://github.com/antidot-framework/antidot-framework/pull/17, and forget it, this PR is perfect;-D Thanks a lot for your help.

**Pull request merged**
